In [1]:
import pandas as pd

data_frame = pd.read_csv("salaries_by_college_major.csv")
data_frame.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [2]:
data_frame.shape

(51, 6)

In [3]:
data_frame.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

In [4]:
data_frame.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [5]:
data_frame.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [6]:
clean_data_frame = data_frame.dropna()
clean_data_frame.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [7]:
max_id = clean_data_frame["Starting Median Salary"].idxmax()
print(max_id)
clean_data_frame["Undergraduate Major"].loc[max_id]

43

'Physician Assistant'

In [8]:
mid_career_median = clean_data_frame["Mid-Career Median Salary"].max()
print(mid_career_median)
clean_data_frame["Undergraduate Major"].loc[clean_data_frame["Mid-Career Median Salary"] == mid_career_median]

107000.0

8    Chemical Engineering
Name: Undergraduate Major, dtype: str

In [9]:
lowest_starting_median = clean_data_frame["Starting Median Salary"].min()
print(lowest_starting_median)
clean_data_frame["Undergraduate Major"].loc[clean_data_frame["Starting Median Salary"] == lowest_starting_median]

34000.0

49    Spanish
Name: Undergraduate Major, dtype: str

In [10]:
# Sorting values and adding columns: Majors with the most potential vs lowest risk
spread_col =clean_data_frame["Mid-Career 90th Percentile Salary"] - clean_data_frame["Mid-Career 10th Percentile Salary"]
clean_data_frame.insert(1, "Spread", spread_col)

In [11]:
clean_data_frame.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [12]:
low_risk = clean_data_frame.sort_values("Spread")
low_risk[["Undergraduate Major", "Spread"]].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [13]:
# Majors with the highest potential
highest_potential = clean_data_frame.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
highest_potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [14]:
# Major with the greatest spread in salaries
highest_spread = clean_data_frame.sort_values("Spread", ascending=False)
highest_spread[["Undergraduate Major", "Spread"]].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [17]:
# Grouping and pivoting data with pandas
print(clean_data_frame.groupby("Group").count())

          Undergraduate Major  Spread  Starting Median Salary  \
Group
Business                   12      12                      12
HASS                       22      22                      22
STEM                       16      16                      16

          Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
Group
Business                        12                                 12
HASS                            22                                 22
STEM                            16                                 16

          Mid-Career 90th Percentile Salary
Group
Business                                 12
HASS                                     22
STEM                                     16

In [18]:
clean_data_frame.groupby("Group").mean()

TypeError: dtype 'str' does not support operation 'mean'

In [19]:
# Number formats in the outputs
pd.options.display.float_format = '{:,.2f}'.format

In [23]:
clean_data_frame.groupby("Group").mean()

TypeError: dtype 'str' does not support operation 'mean'